variable "region" {
  description = "AWS region"
}

variable "vpc_cidr" {
  description = "VPC CIDR"
}

variable "environment" {
  description = "Environment Name"
}

variable "public_subnets_cidr" {
  description = "Public Subnets CIDR's"
}

variable "private_subnets_cidr" {
  description = "Private Subnets CIDR's"
}

variable "instance_count" {
  description = "The number of ec2 instances to be launched"
}

variable "instance_ami" {
  description = "AMI"
}

variable "instance_type" {
  description = "Type of machine"
}

variable "generated_key_name" {
  type        = string
  description = "Key-pair generated by Terraform"
}