variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "environment" {
  description = "Environment Name"
}

variable "vpc_id" {
  description = "VPC ID"
}

variable "bastion_public_ip" {
  description = "public ip of bastion machine"
}

variable "instance_count" {
  description = "The number of ec2 instances to be launched"
}